import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
          <h1 className={styles.title}>
            Hunting Coder
          </h1>
          <Image className={styles.myimg} src="/homeimg.jpg" width={576} height={384}/>
          <p className={styles.description}>
            A blog for hunting coders by a hunting coder
          </p>
        <div className={styles.blogs}>
          <h2>Popular Blog</h2>
          <div className={styles.blogitem}>
            <h3 className="blog-title">
              How to learn JavaScript in 2022?
            </h3>
            <p className="blog-description">
              JavaScript is a Coding language used to design the logic of a Web Page
            </p>
          </div>
          
          <div className={styles.blogitem}>
            <h3 className="blog-title">
              How to learn JavaScript in 2022?
            </h3>
            <p className="blog-description">
              JavaScript is a Coding language used to design the logic of a Web Page
            </p>
          </div>
          
          <div className={styles.blogitem}>
            <h2 className="blog-title">
              How to learn JavaScript in 2022?
            </h2>
            <p className="blog-description">
              JavaScript is a Coding language used to design the logic of a Web Page
            </p>
          </div>
        </div>
        
      </main>
    </>
  )
}
